title: Damien Campagnaud
description: Ressources pédagogiques et projets
theme: jekyll-theme-portfolio

author:
  name: "Damien Campagnaud"
  bio: "Enseignant en SVT | Pédagogie active | Projets scientifiques"
  location: "France"

collections:
  genially:
    output: true
    permalink: /genially/:name/

sass:
  style: compressed
