title: Damien Campagnaud
description: Ressources p√©dagogiques et projets
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

collections:
  genially:
    output: true
    permalink: /genially/:name/
