title: Damien CAMPAGNAUD
description: Cr√©ations Genially et ressources en SVT
url: "https://damiencampagnaud.github.io"
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  genially:
    output: true
    permalink: /genially/:name/
