title: Damien Campagnaud
description: Ressources pédagogiques et projets
remote_theme: pages-themes/cayman@v0.3.0  # thème officiel GitHub Pages
plugins:
  - jekyll-feed

collections:
  genially:
    output: true
    permalink: /genially/:name/

sass:
  style: compressed
