title: Damien Campagnaud
description: Ressources pédagogiques et projets
remote_theme: pages-themes/cayman # version officielle supportée par GitHub Pages
plugins:
  - jekyll-feed

collections:
  genially:
    output: true
    permalink: /genially/:name/
